-- Users Table
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'client') NOT NULL,
    email VARCHAR(255) NOT NULL;
);

-- Clients Table
  CREATE TABLE clients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_id INT NOT NULL,
    company_id VARCHAR(100) DEFAULT NULL,
    company_name VARCHAR(25) DEFAULT NULL,
    ein VARCHAR(9) DEFAULT NULL,
    address VARCHAR(50) DEFAULT NULL,
    city VARCHAR(50) DEFAULT NULL,
    entity_corp VARCHAR(100) DEFAULT NULL,
    state VARCHAR(25) DEFAULT NULL,
    owner_address VARCHAR(100) DEFAULT NULL,
    phone_num VARCHAR(15) DEFAULT NULL;
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Employees Table
CREATE TABLE employees (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    position VARCHAR(255) NOT NULL,
    salary DECIMAL(10, 2) NOT NULL,
    client_id INT NOT NULL,
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

ALTER TABLE clients 
ADD COLUMN company_id VARCHAR(100) DEFAULT NULL,
ADD COLUMN company_name VARCHAR(25) DEFAULT NULL,
ADD COLUMN ein VARCHAR(9) DEFAULT NULL,
ADD COLUMN address VARCHAR(50) DEFAULT NULL,
ADD COLUMN city VARCHAR(50) DEFAULT NULL,
ADD COLUMN entity_corp VARCHAR(100) DEFAULT NULL,
ADD COLUMN state VARCHAR(25) DEFAULT NULL,
ADD COLUMN owner_address VARCHAR(100) DEFAULT NULL,
ADD COLUMN phone_num VARCHAR(15) DEFAULT NULL;

ALTER TABLE clients
ADD COLUMN employee_count INT(0) DEFAULT NULL;